const data ={
    productData:[
        {
            "id":123,
            "address":"г. Воронеж ул.Стар..",
            "date":"23.02.23 ",
            "date1":" 15:00-18:00 ",
            "marka":"M200",
            "metr":"20",
            "som":"200 000",
            "ish":"В пути",
            "tolov_category":"Наличные",
            "tarif":"Эконом",
            "mashina":"3м3",
            "shving":"15м",
            "time":"3",
            "padachi_time":"3",
            "qoshincha":"Пусковая смесь, подвоз на участок",
            "naxri_beton":"5000",
            "narxi_dastafka":"5 000",
            "narxi_qoshimcha":"5 000",
            "jami":"5 000",
            "bonus":"12 000" 
        },
        {
            "id":124,
            "address":"г. Воронеж ул.Стар..",
            "date":"23.02.23 ",
            "date1":" 15:00-18:00 ",
            "marka":"M200",
            "metr":"20",
            "som":"200 000",
            "ish":"В пути",
            "tolov_category":"Наличные",
            "tarif":"Эконом",
            "mashina":"3м3",
            "shving":"15м",
            "time":"3",
            "padachi_time":"3",
            "qoshincha":"Пусковая смесь, подвоз на участок",
            "naxri_beton":"5000",
            "narxi_dastafka":"5 000",
            "narxi_qoshimcha":"5 000",
            "jami":"5 000",
            "bonus":"12 000"
        },{
            "id":125,
            "address":"г. Воронеж ул.Стар..",
            "date":"23.02.23 ",
            "date1":" 15:00-18:00 ",
            "marka":"M200",
            "metr":"20",
            "som":"200 000",
            "ish":"В пути",
            "tolov_category":"Наличные",
            "tarif":"Эконом",
            "mashina":"3м3",
            "shving":"15м",
            "time":"3",
            "padachi_time":"3",
            "qoshincha":"Пусковая смесь, подвоз на участок",
            "naxri_beton":"5000",
            "narxi_dastafka":"5 000",
            "narxi_qoshimcha":"5 000",
            "jami":"5 000",
            "bonus":"12 000"
        }
    ]
}
export default data